module.exports = {
  arc: require('./arc'),
  circle: require('./ellipse').circle,
  cube: require('./cuboid').cube,
  cuboid: require('./cuboid').cuboid,
  cylinder: require('./cylinder'),
  cylinderElliptic: require('./cylinderElliptic'),
  ellipse: require('./ellipse').ellipse,
  geodesicSphere: require('./geodesicSphere'),
  line: require('./line'),
  polygon: require('./polygon'),
  polyhedron: require('./polyhedron'),
  rectangle: require('./rectangle').rectangle,
  roundedCube: require('./roundedCube'),
  roundedCylinder: require('./roundedCylinder'),
  roundedRectangle: require('./roundedRectangle'),
  sphere: require('./sphere'),
  square: require('./rectangle').square,
  star: require('./star'),
//  torus: require('./torus')
}
